### ISSUE TITLE
Does not work with OpenJDK on Windows

### ISSUE THREAD

**Issue by loxal** [melix/jmh-gradle-plugin#103]
```
C:\Users\alex\my\project\intrafind\if-sitesearch   ./gradlew jmh --stacktrace

> Task :jmh
# JMH 1.17.4 (released 195 days ago, please consider updating!)
# VM version: Cannot run program "C:\Users\alex\scoop\apps\openjdk\current\jre\bin\java.exe": CreateProcess error=206, The filename or extension is too long# VM invoker: C:\Users\alex\scoop\apps\openjdk\current\jre\bin\java.exe
# VM options: <none>
# Warmup: <none>
# Measurement: 1 iterations, single-shot each
# Timeout: 10 min per iteration
# Threads: 2 threads
# Benchmark mode: Single shot invocation time
# Benchmark: de.intrafind.sitesearch.jmh.BenchmarkTests.benchmark

# Run progress: 0.00% complete, ETA 00:00:00
# Fork: 1 of 10
<failed to invoke the VM, caught IOException: Cannot run program "C:\Users\alex\scoop\apps\openjdk\current\jre\bin\java.exe": CreateProcess error=206, The filename or extension is too long>

# Run complete. Total time: 00:00:00

Benchmark  Mode  Cnt  Score   Error  Units

Benchmark result is saved to C:\Users\alex\my\project\intrafind\if-sitesearch\build\reports\jmh\results.txt


BUILD SUCCESSFUL in 2s
6 actionable tasks: 1 executed, 5 up-to-date
```

**Comment by loxal** [comment]
Looks like it does not matter whether it's OpenJDK. You just don't support Windows? The test failed for other reasons when executing w/ Windows Bash.

**Comment by loxal** [comment]
Never mind, my fault.

**Comment by akarnokd** [comment]
I've run into the same problem. How did you solve it?

**Comment by loxal** [comment]
@akarnokd I simply got rid of the plugin which I didn't need anyway. This how you run JMH without the plugin which just works:

(1) https://github.com/loxal/muctool/blob/master/service/src/test/java/net/loxal/muctool/jmh/LoadBenchmark.java
(2) https://github.com/loxal/muctool/blob/master/service/build.gradle
```

jmhReport {
    jmhResultPath = project.file("$buildDir/jmh-result.json")
    jmhReportOutput = project.file(buildDir)
}
task runJMH(type: JavaExec) {
    main = "net.loxal.muctool.jmh.LoadBenchmark"
    classpath sourceSets.test.runtimeClasspath
}
tasks.runJMH.finalizedBy tasks.jmhReport

```
...jmhReport is only when you need to generate a visual report.
(3) ./gradlew runJMH $args

**Comment by akarnokd** [comment]
Thanks. I have several benchmarks in the project and don't want to change build.gradle whenever a new one is added. 

`verbosity = "EXTRA"` prints a command line 35k long with all sorts of irrelevant jars. It seems to come from `java.class.path`.

Would a shadow jar help in this case?

**Comment by loxal** [comment]
You do not have to, `main = "net.loxal.muctool.jmh.LoadBenchmark"` refers to an entry class that can specifies an `*` include that will execute all the benchmarks you need with the predefined options.

No clue regarding your other problem.

**Comment by akarnokd** [comment]
I'm using Gradle 4.2.1 and the classpath that JHM prepares for forking contains a lot of gradle components. The first half dozen are the JHM classes and the JAR file containing the test, the rest are part of the project's compilation/environment part. I'm using the plugin with 4.0.2 in another project and there seems to be no excess path problem.

```
-cp, "
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\org.openjdk.jmh\jmh-generator-bytecode\1.19\8a4e09517a2895cc6b290ce84e4f3005f24b4f74\jmh-generator-bytecode-1.19.jar;
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\org.openjdk.jmh\jmh-generator-asm\1.19\ac1a7c4ad2ea587bedf66088d28fec561cea245\jmh-generator-asm-1.19.jar;
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\org.openjdk.jmh\jmh-generator-reflection\1.19\184b84a99634357d38df6d2f43b716366efa41b9\jmh-generator-reflection-1.19.jar;
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\org.openjdk.jmh\jmh-core\1.19\1ea93b88f8154f0a35c16b46d76cfb2febcf4916\jmh-core-1.19.jar;
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\net.sf.jopt-simple\jopt-simple\4.6\306816fb57cf94f108a43c95731b08934dcae15c\jopt-simple-4.6.jar;
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-math3\3.2\ec2544ab27e110d2d431bdad7d538ed509b21e62\commons-math3-3.2.jar;
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\5.0.3\dcc2193db20e19e1feca8b1240dbbc4e190824fa\asm-5.0.3.jar;C:\Users\akarnokd\git\RxJava\build\libs\rxjava-2.2.0-SNAPSHOT-jmh.jar;
------------ these are practically unnecessary:
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\ru.vyarus\gradle-animalsniffer-plugin\1.2.0\2858c5218f1116b2513554346596a05fa6c58c70\gradle-animalsniffer-plugin-1.2.0.jar;
C:\Users\akarnokd\.gradle\caches\modules-2\files-2.1\gradle.plugin.nl.javadude.gradle.plugins\license-gradle-plugin\0.13.1\c270280ba46f95804a3aee4698725718ade3035c\license-gradle-plugin-0.13.1.jar;
...
C:\Users\akarnokd\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju\gradle-4.2.1\lib\gradle-tooling-api-4.2.1.jar"
```

(added newlines for readability).

**Comment by akarnokd** [comment]
Is there a way to prevent Gradle itself from passing in that many of its runtime jar dependencies? For example, have this plugin prepare the jar file and basically use ProcessBuilder manually to execute JMH and thus control the arguments instead of the Gradle runner?

**Comment by jjYBdx4IL** [comment]
Same problem here. Version 1.21. Not sure why C:\cygwin64\home\work\.sdkman\candidates\java\8.0.172-zulu\jre\bin\java.exe should be too long. Maybe set working directory to parent directory and just run java.exe?

**Comment by akarnokd** [comment]
I worked out a workaround with JMH itself so starting from JMH 1.20, you can add an extra `-Djmh.separateClasspathJAR=true` parameter and it should work:

https://github.com/akarnokd/akarnokd-misc/blob/master/build.gradle#L203

**Comment by jjYBdx4IL** [comment]
Is there a way to do this using OptionsBuilder?
