### ISSUE TITLE
Support kotlin multiplatform builds / custom main sourceset

### ISSUE THREAD

**Issue by altavir** [melix/jmh-gradle-plugin#140]
I've hit the wall with new [kotlin multiplatform gradle model](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#setting-up-a-multiplatform-project).

The problem arises because jmh by default depends on `main` sourceset, which is not present in multiplatform model and usually replaced by something like `jvmMain`. I think it could be solved simply by allowing to declare custom name for main and main test sourcesets.

**Comment by bnvinay92** [comment]
@melix is this something you would be open to?

**Comment by altavir** [comment]
I think this issue could be closed because benchmarking in Kotlin is now covered in https://github.com/Kotlin/kotlinx-benchmark. And it includes multiplatform support.
