### ISSUE TITLE
New deprecation warnings with Gradle 6.0-rc-1

### ISSUE THREAD

**Issue by huxi** [melix/jmh-gradle-plugin#158]
The following is printed while executing `compileJmhJava` with `--warning-mode all` Gradle option with Gradle 6.0-rc-1 and `me.champeau.gradle:jmh-gradle-plugin:0.4.8`.

```
The testCompile configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the testCompileClasspath configuration instead.
```

**Comment by melix** [comment]
This is fixed in 0.5.0.
