### ISSUE TITLE
Add option to report progress

### ISSUE THREAD

**Issue by karalabe** [melix/jmh-gradle-plugin#17]
The plugin always passes the human readable output file to jmh. This unfortunately results in JMH not displaying any output onto the console/stdout. This can become quite annoying if running from within an IDE (or trying to follow progress on a CI server too).

Would it be possible to add an option to multiplex the output to STDOUt too?

**Comment by vyazelenko** [comment]
@karalabe You can force output to console if you unset ```humanOutputFile``` property:
```groovy
jmh {
  humanOutputFile = null
}
```
But actually PR #33 will do it by default.
