### ISSUE TITLE
multi-project setups should skip sub-projects that don't have jmh benchmarks

### ISSUE THREAD

**Issue by kyle-downey** [melix/jmh-gradle-plugin#20]
Right now you need to target each specific project, e.g. 'gradle core:jmh' to run all the JMH benchmarks under the core sub-project. Ideally you should be able to apply the plugin at the top level and then just run 'gradle jmh' to run all of them.

**Comment by aalmiray** [comment]
By separation of concerns the application of the plugin to a particular subproject must be decided outside of the plugin.
