### ISSUE TITLE
Usage of depricated setCanBeResolved(true)

### ISSUE THREAD

**Issue by sergeykad** [melix/jmh-gradle-plugin#254]
During the build, Gradle complains about the following:

The resolvable usage is already allowed on configuration ':my-module:jmhRuntimeClasspath'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Remove the call to setCanBeResolved(true), it has no effect. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#redundant_configuration_usage_activation

**To Reproduce**
1. Run build with JMH plugin

**Comment by Goooler** [comment]
This had been fixed in #252.
