### ISSUE TITLE
jmh.jmhVersion definition does not work properly

### ISSUE THREAD

**Issue by bensteinert** [melix/jmh-gradle-plugin#26]
Hi,
I'm currently working with the jmh-gradle plugin. As JMH 1.3.3 was released few days back I tried to use the jmhVersion property which was introduced by a former pull request. The implementation actually does not work, because the property gets set after the dependencies have been added to the configuration. I implemented the dependency definition in a beforeResolve action and for that upgraded to gradle 2.2.1. Please find the fix in my fork. I will provide a pull request the next days to get it merged back to the main project. I first would like to write some additional tests for that.

**Comment by vyazelenko** [comment]
Issue can be closed as it works since release **0.2.0**.

**Comment by melix** [comment]
Thanks for the heads up.
