### ISSUE TITLE
'jmh' task does not include tests folder

### ISSUE THREAD

**Issue by alexd84** [melix/jmh-gradle-plugin#31]
Jmh task does not include test folder sources and resources, it makes benchmarks dependent on test classes fail to compile. Could you please let me to contribute the fix?

**Comment by superbobry** [comment]
You need to change the `includeTests` flag, which is set to `false` by default,

**Comment by alexd84** [comment]
includeTests just includes test classes into jar file. 
The problem is that it does not add test sources to classpath when compiling benchmark classes. So if my benchmark class depends on test classes it fails with ClassNotFoundException.

**Comment by superbobry** [comment]
I see, this is indeed a different issue. Why don't you submit your existing solution as a PR?

**Comment by ben-manes** [comment]
It also does not include dependencies. The following seems to work more reliably than the `includeTests` flag.

```gradle
sourceSets {
  jmh.java.srcDirs += sourceSets.test.java.srcDirs
}

dependencies {
  afterEvaluate {
    jmh configurations.testCompile.allDependencies
  }
}
```

**Comment by alexd84** [comment]
pr submitted: https://github.com/melix/jmh-gradle-plugin/pull/37

**Comment by vyazelenko** [comment]
PR #37 looks. I fully agree that JMH should depend on test sources by default. With this PR ```includeTests``` flag can be dropped.
@melix what do you think?
