### ISSUE TITLE
Shadow plugin detection is broken when using new plugin DSL

### ISSUE THREAD

**Issue by marshallpierce** [melix/jmh-gradle-plugin#38]
If I include this plugin the old way:

```
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath "me.champeau.gradle:jmh-gradle-plugin:0.2.0"
  }
}
...
apply plugin: 'me.champeau.gradle.jmh'
```

then jmhJar is built correctly, and includes services entries.

If I include it the new way:

```
plugins {
  id 'me.champeau.gradle.jmh' version '0.2.0'
}
```

then jmhJar is built as just a jar that excludes services entries, which breaks my app. (On a related note, why are you excluding services files when assembling a jar without the shadow plugin?)

I tried to investigate a little (I theorize that perhaps classloader isolation with the new DSL is the cause here) but I couldn't get far since I couldn't figure out how to depend on a local snapshot with the plugin DSL. I did notice that PluginContainer claims to no longer be the preferred way to look for plugins, so perhaps in JMHPlugin:58 you want something like this:

```
        if (!project.plugins.pluginManager.hasPlugin('com.github.johnrengelman.shadow')) {
```

That's just a theory based on my assumption that the recommended way to do it knows how to cross the DSL's plugin boundaries.

**Comment by bensteinert** [comment]
Hi Marshall,
ok different topics. Let's get them sorted:
**New plugin DSL and local plugin snapshots:** As far as I know, the still incubating DSL extension for plugins cannot be used with other repositories than the gradle plugin repo. Means, for local snapshots, you need to switch back to the common buildscript block.
**New plugin DSL and problems with shadow plugin:** The issue title relates problems with the shadow plugin when using the new plugin DSL. Think there is no link between the new plugin DSL and the issues you have.
**META-INF/services gets excluded when using jmh-gradle-plugin without shadow plugin: ** Yes, that is something I can confirm. Maybe other authors can tell more why. But finally you are right, there is a deviation in the exclude list, when building with and without shadow plugin. Think in the end it should be up to the user to explicitly exclude files from the jar if needed, independently of the jar creation method. Melix, what do you think? If time permits, I create a pull request for that issue.
**usage of PluginContainer in JMHPlugin:** Think the usage of PluginContainer is acceptable and more stable than the usage of the incubating PluginManager which would also break backwards compatibility with 2.2.1. In the long run I could imagine, that PluginContainer gets seamlessly replaced by the PluginManager behind the scenes (at least when looking at the interfaces.)

**Comment by marshallpierce** [comment]
I'm not sure how you can claim that there's no link between using the DSL and the shadow plugin detection. Let me present a simplified version:

use new plugin DSL => doesn't detect shadow plugin
use old "apply" syntax => detects shadow plugin

Obviously there is a link somewhere.

**Comment by marshallpierce** [comment]
That's really a shame that there isn't a way to use other repositories with the new DSL... That will make this hard to track down. :(

**Comment by bensteinert** [comment]
Hi Marshall,
I actually tried it, that's why I claim this ;). Tried Gradle 2.4 and 2.6 snapshot with both plugin definitions and in both cases, the right if/else branch is taken in JMHPlugin.

**Comment by bensteinert** [comment]
Short amendment to you 2nd comment. Not a shame at all. Gradle people are currently working on those things actively, which means that it is neither yet stable nor feature complete. It is more of a fortune, that we can try it out already and give early feedback. Imho I would stick to the classic apply() approach in the meantime because it is far away from being deprecated.

**Comment by marshallpierce** [comment]
Doh! I retract my comment; it is not at all obvious that there is a link. ;)

I'll dig in more later but if you have time you can try playing with the project that I had the problem in: https://bitbucket.org/marshallpierce/jersey2-metrics

When it doesn't detect shadow, service files get excluded and the JMH benchmarks break because HK2 can't initialize itself.

**Comment by bensteinert** [comment]
Hi again,
took a look at your project and, wow, didn't know that 'Micro' in microbenchmark can be that Macro :smile:. 
Anyways, I think the basic idea of your issue stays valid. If someone explicitly wants to control includes and excludes for the jmhJar, he should be able to do so. @melix, @vyazelenko what do you think about that idea? @vyazelenko you originally implemented the exclusion of the META-INF/services folder, for which reason?

So ong 
Cheers
Benni

**Comment by marshallpierce** [comment]
Did you try toggling between the different ways of applying the plugin and see the different behavior?

**Comment by bensteinert** [comment]
No difference. Successfully verified the fix with your project as well :)
![screen shot 2015-06-22 at 22 11 56](https://cloud.githubusercontent.com/assets/1677465/8291748/c62602ae-192b-11e5-82e5-eaab679fcd42.png)
Please try it as well: https://github.com/comsysto/jmh-gradle-plugin/tree/jar_excludes_issue_38

**Comment by marshallpierce** [comment]
The issue is quite reproducible still for me.

With current master (ae6a133) of jersey2-metrics:

```
./gradlew clean jmh
```

works correctly.

Apply this to benchmark-svc/build.gradle:

```
   dependencies {
     // has to be included the old way to make shadow plugin detection work
-    classpath "me.champeau.gradle:jmh-gradle-plugin:0.2.0"
+//    classpath "me.champeau.gradle:jmh-gradle-plugin:0.2.0"
   }
 }

 plugins {
+  id "me.champeau.gradle.jmh" version '0.2.0'
   // if this plugin is available, jmh plugin does a better job of creating a fat jar
   id 'com.github.johnrengelman.shadow' version '1.2.1'
 }
```

Once again, `./gradlew clean jmh`
and now I get:

```
WARNING: Cannot find a default implementation of the HK2 ServiceLocatorGenerator
```

and in the JMH log:

```
# Warmup Iteration   1: <failure>

java.lang.IllegalStateException: No generator was provided and there is no default generator registered
        at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:266)
        at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:230)
        at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
        at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:123)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:324)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:298)
        at org.mpierce.jersey2.metrics.jmh.MetricsJmhBenchmark$BenchmarkState.setUp(MetricsJmhBenchmark.java:67)
        at org.mpierce.jersey2.metrics.jmh.generated.MetricsJmhBenchmark_measure._jmh_tryInit_f_benchmarkstate2_G(MetricsJmhBenchmark_measure.java:498)
        at org.mpierce.jersey2.metrics.jmh.generated.MetricsJmhBenchmark_measure.measure_Throughput(MetricsJmhBenchmark_measure.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by bensteinert** [comment]
Aaaaah, I think now I got it why you get this behavior. Please let the shadow plugin come first in your plugins list... Otherwise the if/else branch will surely fail because the shadow existence check will be done immediately on plugin.apply(). Sorry, that I did not get it earlier.

**Comment by marshallpierce** [comment]
Aha! Excellent, thanks. Makes perfect sense, in retrospect... Now, feel free to hijack this issue to fix the jar / shadow inconsistency. :)

**Comment by vyazelenko** [comment]
@bensteinert  I **didn't** implement ```WEB-INF/services``` folder exclusion. It was there since [Initial working version of the plugin](https://github.com/melix/jmh-gradle-plugin/commit/fc247784a6ce5a19d0d6023a7c174118d2ebc9de) and was implemented by @melix.
As I already commented on #42 my guess is that this was done in order to avoid generating broken fat jar when multiple dependencies contain such ```WEB-INF/services``` folder. 

Anyway it seems that in order to handle ```WEB-INF/services``` folder properly one should use [shadow](https://github.com/johnrengelman/shadow) plugin.

**Comment by vyazelenko** [comment]
TODO:
- [ ] Use the same excludes list for shadow/non-shadow case
- [ ] Do not exclude `/META-INF/services/` by default
- [ ] Check if we can solve plugin order problem, i.e. Shadow must be declared before JMH plugin

/cc @aalmiray

**Comment by vyazelenko** [comment]
PR #47 implements first 2 items in TODO list.

**Comment by vyazelenko** [comment]
PR #53 brings same META-INF excludes in all cases (i.e. previous PR #47)

**Comment by aalmiray** [comment]
The solution is to apply the `shadow` plugin first, before `jmh`.
