### ISSUE TITLE
JMH jars not visible when importing to IntelliJ

### ISSUE THREAD

**Issue by jerzykrlk** [melix/jmh-gradle-plugin#39]
I had a couple issues using this plugin in an IDEA project. I'm not using Gradle's `IDEA Plugin`, and would prefer to stay with IntelliJ's default Gradle handling.

The issues were:
* JMH jars not visible in the IDE - which made writing benchmarks quite challenging,
* once I added both JMH jars to compile configuration, I couldn't properly execute the jmh task any more. I kept getting `No matching benchmarks. Miss-spelled regexp?`.

I fixed these issues in my local branch somehow. Would you happen to be interested in incorporating them into your plugin?

**Comment by ben-manes** [comment]
I'm pretty sure all you need is.

```gradle
apply plugin: 'idea'

idea.module {
  scopes.PROVIDED.plus += [ configurations.jmh ]
}
```

**Comment by jerzykrlk** [comment]
Hi Ben.
This is going to work fine, if you generate your IDEA config files with Gradle. 

For various reasons, I'd rather not generate IDEA setup from within Gradle, but rather rely on IDE support for Gradle builds. And, IDEA won't properly import a JMH project properly by default.

See https://github.com/melix/jmh-gradle-plugin/pull/40 for a fix.

**Comment by melix** [comment]
Yeah I'm not very fond of the solution in #40. There's a leaking
abstraction in there. I still favour the workaround here. IDE support is
what it is, far from being able to understand the whole Gradle model, which
is why I prefer "gradle idea", which is something you normally do once in a
while (when dependencies change for example).

**Comment by ben-manes** [comment]
The fix that I suggested doesn't require generating from Gradle. The import will understand the directive, so no special hacking is needed to play nicely with the IDEs.

**Comment by jerzykrlk** [comment]
Ok, I've added `apply plugin: 'idea'` to the project and everything worked fine. 
Looks pretty obvious, now.

Thank you!

**Comment by ben-manes** [comment]
@jerzykrlk
I think this should stay open. Either the documentation or plugin should be updated to improve usability.

@melix 
Please consider adding this tweak to your plugin to improve usability. Obviously many users won't realize how to resolve this without either telling them in the `README` or detecting and handling this directly. Similarly for Eclipse (see #35), which I needed for my own sanity and added the IntelliJ fix by request of users building my [library](https://github.com/ben-manes/caffeine).

**Comment by jerzykrlk** [comment]
I have a little Maven background and expected the `idea` plugin to behave in a way similar to Maven's Eclipse plugin.

Existing README does not suggest that users could get a little extra with adding IDEA plugin. I guess a section in the docs covering IDE integrations, should be enough.
