### ISSUE TITLE
Compiler options for benchmarks

### ISSUE THREAD

**Issue by mjpt777** [melix/jmh-gradle-plugin#41]
How do I pass compiler arguments when building the benchmarks?

**Comment by vyazelenko** [comment]
@mjpt777 Can you add an example of what exactly you want to do? How would you do it directly using command line?

**Comment by mjpt777** [comment]
I worked out how to do this. It was failing because of an issue with passing `-XDignore.symbol.file`

The following makes it possible by forking.

```
ext {
    javaCompilerExecutable = System.env['JAVA_HOME'] ? System.env['JAVA_HOME'] + '/bin/javac' : 'javac'
}

compileJmhJava {
    options.compilerArgs << '-XDignore.symbol.file'
    options.fork = true
    options.debug = true
    options.forkOptions.executable = javaCompilerExecutable
    options.warnings = false
}
```
