### ISSUE TITLE
Doesn't work with IntelliJ IDEA 15

### ISSUE THREAD

**Issue by blacklion** [melix/jmh-gradle-plugin#43]
IntelliJ IDEA 14 could import gradle project with this plugin, with some problems: it doesn't understand jmhVersion (puts dependency to 1.3.2, not configured one) and hase source / dependency scope mismatch (easily fixable by hands).

But IDEA 15 could not properly import such project at all: it doesn't see any JMH-related dependencies.

**Comment by vyazelenko** [comment]
@blacklion do you have sample project to reproduce the problem?

**Comment by blacklion** [comment]
Looks like adding "idea" gradle plugin to project helps for IDEA 14, and IDEA 15 has problems with dependencies in gradle projects even without JMH :(

**Comment by vyazelenko** [comment]
@aalmiray, it seems that issue can be closed.

**Comment by portenez** [comment]
I haven't been able to make it work with IDEA 15. I added the IDEA plugin, but didn't resolve the issue.

**Comment by vyazelenko** [comment]
@portenez Can you post your `build.gradle` file?

**Comment by portenez** [comment]
I'll post that as soon as I have a chance.

**Comment by portenez** [comment]
I was able to make IDEA 15 work by adding the following
```groovy
apply plugin: 'idea'

idea {
    scopes.COMPILE.plus += [configurations.jmh]
}
```

I need to remove all the propietary stuff from my **build.gradle**, but I'll post it asap. BTW thanks for this plugin.

**Comment by portenez** [comment]
I apologize, it's working on IDEA15, all that it needs is

```groovy
apply plugin: 'idea'
```

If the plugin is there, then idea can compile the classes under src/jmh/java

**Comment by vyazelenko** [comment]
@aalmiray can be closed
