### ISSUE TITLE
Profiler commandline option in jmh have changed

### ISSUE THREAD

**Issue by npetzall** [melix/jmh-gradle-plugin#44]
The way to specify profilers in JMH has changed in changeset 15cd0bde0cee.

http://hg.openjdk.java.net/code-tools/jmh/rev/15cd0bde0cee

Instead of list separated by "," it should now be repeated -prof  for each profiler.

profilers are used in the jmh task.

So this should affect version 1.10 and later.

**Comment by vyazelenko** [comment]
Fixed by @aalmiray with df498a8

**Comment by vyazelenko** [comment]
@aalmiray you should close this one.
