### ISSUE TITLE
Runtime classpath from the jmh sourceset should be taken into account when running tests

### ISSUE THREAD

**Issue by ivansenic** [melix/jmh-gradle-plugin#52]
If I declare something like:
```
sourceSets {
	jmh {
		java {
			compileClasspath += project(':shared').sourceSets.main.output
			runtimeClasspath += project(':shared').sourceSets.main.output
		}
	}
}
```

compile class-path will be correctly  taken into account when compiling the files from the jmh sourceset. However, the runtime class-path will not be considered when running tests, thus tests end up with _ClassNotFoundException_.

The workout that works for me is:
```
dependencies {
	jmh project(':shared')
}
```

but I would still expect that the _runtimeClasspath_ is taken into account.

**Comment by aalmiray** [comment]
I think this may have to do with packaging of all dependencies (fatjarring) in a single jar. If a dependency is set directly on the `runtimeClasspath` then it'll be invisible to the fatjar process( regardless of simple JAR or shadowJar). The workaround you mentioned is actually the correct way to specify dependencies that should be part of the fatjar.

@vyazelenko: do you have any other comments on this one?

**Comment by vyazelenko** [comment]
No, no comments from my side. Can be closed.

**Comment by vyazelenko** [comment]
This seems to be relevant with multi-project build. Perhaps should be looked at together with #20.
