### ISSUE TITLE
Bug with passing multiple parameters to jmh

### ISSUE THREAD

**Issue by baohuahuang1** [melix/jmh-gradle-plugin#58]
If I need to pass multiple parameters to jmh with benchmarkParameters =  [:], for example:

benchmarkParameters =  [key1:value1, key2:value2, key3:value3]

The command line argument passed to the jmh main function looks like:

-p key1=value1,key2=value2,key3=value3

And the jmh main function is only able to get the first parameter listed.

I am using jmh 1.11, base on the source code of org.openjdk.jmh.runner.options.CommandLineOptions, the -p option is expected to be used once per parameter: 

        OptionSpec<String> optParams = parser.accepts("p", "Benchmark parameters. This option is expected to be used " +
                "once per parameter. Parameter name and parameter values should be separated with equals sign. " +
                "Parameter values should be separated with commas.")
                .withRequiredArg().ofType(String.class).describedAs("param={v,}*");

So to be able to pass multiple parameters to jmh the command line arguments to jmh main function should actually be:

-p key1=value1 -p key2=value2 -p key3=value3

Comma is used to pass multiple values to a single parameter, and a new jmh benchmark will be executed for each value.

Would be great to fix this issue.

**Comment by aalmiray** [comment]
Fixed with https://github.com/melix/jmh-gradle-plugin/commit/d8d4e083ea6f70112ca5d50861b4f63d88164da2

**Comment by baohuahuang1** [comment]
Thanks for the quick fix!
