### ISSUE TITLE
Using jmh gradle plugin with eclipse

### ISSUE THREAD

**Issue by IceMan81** [melix/jmh-gradle-plugin#60]
Has anyone successfully used the plugin with eclipse? When I try to open my gradle project which uses the jmh plugin, eclipse does not add the jmh jar as a dependency. So, eclipse complains about all the jmh annotations on my benchmark classes. This all works correctly in Idea. So, this is an eclipse issue and not a plugin issue. I'm looking for any advice on making this work with eclipse. Ofcourse, I could add the jmh dependency explicitly but before I do that I want to be sure there is better solution. I've colleagues who use Eclipse, so I'm trying to make sure it works in eclipse correctly. 

I'm using the latest Eclipse 4.5 with the latest Buildship Gradle plugin for eclipse.

**Comment by vyazelenko** [comment]
@IceMan81 which version of jmh-gradle-plugin are you using? Eclipse support (i.e. #35) is only available in latest release [0.3.0](https://github.com/melix/jmh-gradle-plugin/releases/tag/RELEASE_0_3_0).

**Comment by IceMan81** [comment]
@vyazelenko :) I just found that out a couple of hours back when it started working after I upgraded to 0.3.0. I was using 0.2.0 when I posted this.
