### ISSUE TITLE
benchmarkMode cannot handle multiple values

### ISSUE THREAD

**Issue by steppinrazor** [melix/jmh-gradle-plugin#63]
JMH has the ability to specify multiple benchmarkModes but the Gradle plugin configuration can only handle a single value. PR #62 fixes this according to below:

*Before*

```java
jmh{
    benchmarkMode = 'thrpt'
    ....
}
```

*After*

```java

jmh{
    benchmarkMode = ['thrpt', 'ss']
    ....
}
```

**Comment by aalmiray** [comment]
Fixed with #62
