### ISSUE TITLE
0.3.0 on bintray or mavencentral?

### ISSUE THREAD

**Issue by MikaelUmaN** [melix/jmh-gradle-plugin#71]
I love this plugin.

Is it possible to make it so releases are uploaded to bintray and mavencentral as well? Currently latest is only 0.2.0

**Comment by ddimtirov** [comment]
https://discuss.gradle.org/t/jmh-plugin-0-3-0-released-but-not-available-from-plugins-gradle-org-m2/16518

**Comment by vyazelenko** [comment]
See also discussion in #70

**Comment by ben-manes** [comment]
Gradle's plugin repository does not create `maven-metadata.xml` properly or update it after a release. This results in the dynamic versions or tools like the gradle-versions-plugin being unable to detect updates. Unfortunately the Gradle team has been unresponsive. So users may not be aware of your updates if they have tried to automate the process, unless you also deploy elsewhere like bintray.

**Comment by melix** [comment]
Sorry guys for the late comment. I think I probably made a mistake in the group id when I released the plugin (although I don't understand how). To use 0.3.0 you can do this:

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'gradle.plugin.me.champeau.gradle:jmh-gradle-plugin:0.3.0'
    }
}

apply plugin: 'me.champeau.gradle.jmh'
```

**Comment by bensteinert** [comment]
Hi all,
I would also appreciate to fetch the latest version from bintray! :) Thx!

**Comment by melix** [comment]
I am curious why you want to fetch it from Bintray instead of the plugin portal?

**Comment by bensteinert** [comment]
Im not directly applying it as a plugin, but include it as a compile-time dependency in my own plugin project (https://github.com/comsysto/crolabefra-java). When I now apply my wrapper plugin, the actual consuming projects need to be changed (the plugins repo needs to be added additionally).

**Comment by melix** [comment]
Right, but even for this use case you don't need Bintray. Just remove the `apply` and you will find it on classpath.

**Comment by ddimtirov** [comment]
@melix - many people can not use the plugin portal directly because of regulatory reasons (i.e. preserving a copy of everything needed to reproduce a release.)

There is a long standing request that Gradle supports the newer plugin DSL syntax with proxying repository managers.

Besides that, it looks like the repo URL on the plugin portal redirects to jcenter...

**Comment by ddimtirov** [comment]
Additionaly, for teams using BOM or dependency locking, the change of the organization is not as trivial. 

I.e. the red tape for procuring a new artifact vs new version of approved artifact.

Right now I have patched the resolution strategy in the shared unit script, but I really hope it gets fixed soon...

**Comment by melix** [comment]
The change in organization is not wanted anyway. I'm not sure it is related to the plugin portal in any way, as I said I probably made a mistake when publishing. The plugin portal repo can be used as a regular m2 repo in any case. So I was curious why _in this case_ you wanted to use bintray, because the artifacts are available there.

The use case where you don't want to use the plugin portal _at all_ is very different though.

**Comment by ddimtirov** [comment]
We are already proxying the plugin portal as a regular m2 repo and it is not working (in fact it redirects to jcenter). 

I have reported the problem a while ago - have a look at this post for example how to reproduce with curl. (Apologies for the crossposting)

https://discuss.gradle.org/t/jmh-plugin-0-3-0-released-but-not-available-from-plugins-gradle-org-m2/16518

**Comment by melix** [comment]
Np. I'm not sure what happens here. I don't see how I could have made a mistake in the groupId. On the other hand it seems very strange that I am the only one with this issue..

**Comment by melix** [comment]
So I think I understand now. Checking with the team, but I think the example in https://plugins.gradle.org/docs/publish-plugin is confusing. It seems to indicate that the `group` will be used, but it's not: the `groupId` when using the plugin publish plugin is generated from the plugin id. The "full example" shows how to keep your `groupId`.

@aalmiray if you have pending PRs, might be worth merging before we try a 0.3.1 release to fix this.

**Comment by aalmiray** [comment]
PR #74 fixes these problems

**Comment by aalmiray** [comment]
@melix we can go for a new release. Please try the `publishRelease` task to push releases to both plugin portal and bintray :smile:

**Comment by vyazelenko** [comment]
@aalmiray , @melix task `publishRelease` was lost when PR #74 was merged. I've added PR #77 that adds it back.

Or one can simply execute:
```bash
gradlew clean bintrayUpload publishPlugins
```

**Comment by vyazelenko** [comment]
@melix when do you plan to release `0.3.1`? It is release confusing working with broken `0.3.0` release. Also `0.3.1` contains some important fixes.

**Comment by leventov** [comment]
Any update on this?

**Comment by vyazelenko** [comment]
@melix , @aalmiray ping! We really need to have a new `0.3.1` release.

**Comment by aalmiray** [comment]
The `0.3.1` release is already available at Gradle plugin portal (https://plugins.gradle.org/plugin/me.champeau.gradle.jmh).

OTOH @melix's bintray repository contains `0.2.0` as the latest (https://bintray.com/melix/gradle-plugins/jmh-gradle-plugin).

**Comment by lex-em** [comment]
@melix your artifact does not uploaded, can you retry?

**Comment by lex-em** [comment]
`buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'me.champeau.gradle:jmh-gradle-plugin:0.3.1'
    }
}

apply plugin: 'me.champeau.gradle.jmh'`

works fine

**Comment by MikaelUmaN** [comment]
Closing based on last comment.
