### ISSUE TITLE
Up to date, minimal working example of a JMH+Gradle project?

### ISSUE THREAD

**Issue by cogumbreiro** [melix/jmh-gradle-plugin#98]
Hi,

I am wondering if there's a minimal working example of a JMH project using Gradle.

All my examples were bitten by this error, so I'm a bit lost here:
```
* What went wrong:
An exception occurred applying plugin request [id: 'me.champeau.gradle.jmh', version: '0.4.2']
> Failed to apply plugin [id 'me.champeau.gradle.jmh']
   > Could not generate a proxy class for class me.champeau.gradle.JMHPluginExtension.

```
I've found  the repository below, but it seems to be really outdated:

https://github.com/melix/jmh-gradle-example

**Comment by melix** [comment]
Are you using Gradle 4.0 ? The latest version of the plugin is only working with Gradle 4.+. I updated the example project, let me know if it helps.

**Comment by cogumbreiro** [comment]
That worked, thanks!
